# Generated by Django 5.2.6 on 2025-11-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='end_date',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='collection',
            name='start_date',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='piece',
            name='date',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
