# Generated by Django 5.2.6 on 2025-11-19 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_collection_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.piece'),
        ),
    ]
