# Generated by Django 5.2.6 on 2025-11-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_piece_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='collections',
            field=models.ManyToManyField(to='api.collection'),
        ),
        migrations.AddField(
            model_name='piece',
            name='media',
            field=models.ManyToManyField(to='api.medium'),
        ),
    ]
