# Generated by Django 5.2.6 on 2025-11-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_piece_collections_piece_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piecesmedia',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='piecesmedia',
            name='piece',
        ),
        migrations.AddField(
            model_name='piece',
            name='filename',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.DeleteModel(
            name='PiecesCollections',
        ),
        migrations.DeleteModel(
            name='PiecesMedia',
        ),
    ]
