# Generated by Django 5.2.8 on 2025-11-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_piecesmedia_medium_remove_piecesmedia_piece_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='location',
            field=models.CharField(blank=True, max_length=65),
        ),
    ]
