# Generated by Django 5.2.8 on 2025-11-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_collection_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='end_date',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='location',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
    ]
