# Generated by Django 5.2.8 on 2025-11-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_collection_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='collections',
            field=models.ManyToManyField(blank=True, null=True, to='api.collection'),
        ),
    ]
