# Generated by Django 5.2.8 on 2025-11-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_piece_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='collections',
            field=models.ManyToManyField(blank=True, to='api.collection'),
        ),
    ]
