# Generated by Django 5.2.8 on 2025-11-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_piece_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='use_as_wallpaper',
            field=models.BooleanField(default=False),
        ),
    ]
