# Generated by Django 5.2.8 on 2025-12-12 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_piece_use_as_wallpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='end_date',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='start_date',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='piece',
            name='date',
            field=models.CharField(blank=True, default=None, max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.piece'),
        ),
    ]
