# Generated by Django 5.2.8 on 2025-12-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_collection_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='collections', to='api.collection'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='media',
            field=models.ManyToManyField(related_name='media', to='api.medium'),
        ),
    ]
