# Generated by Django 5.2.8 on 2025-12-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_piece_collections_alter_piece_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='date',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
    ]
